global:
  resolve_timeout: 5m
route:
  # When a new group of alerts is created by an incoming alert, wait at
  # least 'group_wait' to send the initial notification.
  # This way ensures that you get multiple alerts for the same group that start
  # firing shortly after another are batched together on the first
  # notification.
  group_wait: 10s
  # When the first notification was sent, wait 'group_interval' to send a batch
  # of new alerts that started firing for that group.
  group_interval: 30s
  # If an alert has successfully been sent, wait 'repeat_interval' to
  # resend them.
  repeat_interval: 30m
  # A default receiver
  receiver: "alertmanager-bot"

  # All the above attributes are inherited by all child routes and can
  # overwritten on each.
  routes:
    - receiver: "alertmanager-bot"
      group_wait: 10s
      group_by: [alertname,level]
      match_re:
        level: critical|warning|info
      continue: true

receivers:
  - name: "alertmanager-bot"
    webhook_configs:
      - url: 'http://alertmanager-bot:9091'
        send_resolved: true
