# my global config
global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 30s # Evaluate rules every 30 seconds. The default is every 1 minute.(  # A short evaluation_interval will check alerting rules very often.
  # It can be costly if you run Prometheus with 100+ alerts.)

# Alertmanager configuration
alerting:
  alertmanagers:
    # Sets the `Authorization` header on every request with the
    # configured username and password.
    # password and password_file are mutually exclusive.
    - scheme: http
      basic_auth:
        username: fx
        password: fxcore
      static_configs:
        - targets:
            - alertmanager:9093

rule_files:
  - "/etc/prometheus/rules/*.yml"

scrape_configs:
#  - job_name: "node-exporter"
#    honor_timestamps: true
#    scrape_interval: 5s
#    scrape_timeout: 5s
#    metrics_path: /metrics
#    scheme: http
#    static_configs:
#      - targets: [ "node-exporter:9100"]

  - job_name: "fx-chain-node"
    honor_timestamps: true
    scrape_interval: 3s
    scrape_timeout: 3s
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets: [ "192.168.98.202:26660"]
        labels:
          name: val-01
          chain_id: fxcore
#      - targets: [ "192.168.98.100:26660"]
#        labels:
#          name: val-02
#          chain_id: fxcore
