http_server_config:
  http2: false
# Usernames and passwords required to connect to Prometheus.
# Passwords are hashed with bcrypt: https://github.com/prometheus/exporter-toolkit/blob/master/docs/web-configuration.md#about-bcrypt
basic_auth_users:
  # fx: fxcore
  fx: $2y$10$pxrTMPnBJj.OzWTaT7lDOOCd9PNPKls0mTtKLAAKETnmEpQcWdWoG
