# metrics docs: https://docs.tendermint.com/master/nodes/metrics.html
groups:
  - name: fx-chain-alerts
    rules:
      - alert: The fx chain node service
        expr: up{job="fx-chain-node"} != 1
        for: 0m
        labels:
          level: critical
        annotations:
          description: "The fx chain node service not found"

      - alert: The fx chain consensus height
        expr: tendermint_consensus_height - (tendermint_consensus_height offset 1m) == 0
        for: 0m
        labels:
          level: critical
          monitor: tendermint_consensus_height
        annotations:
          description: "The fx chain node does not generate a block for 1 minute"

      - alert: The fx chain consensus validators
        expr: sum(tendermint_consensus_validators - (tendermint_consensus_validators offset 1m) != 0) by (job)
        for: 1m
        labels:
          level: critical
          monitor: tendermint_consensus_validators
        annotations:
          description: "The fx chain consensus validators has changed, current: {{$value}}"

      - alert: The fx chain node latest block height
        expr: tendermint_consensus_latest_block_height - (tendermint_consensus_latest_block_height offset 2m) == 0
        for: 0m
        labels:
          level: critical
          monitor: tendermint_consensus_latest_block_height
        annotations:
          description: "The fx chain node block height does not increase for 2 minutes"

      - alert: The fx chain node last signed height
        expr: tendermint_consensus_validator_last_signed_height - (tendermint_consensus_validator_last_signed_height offset 2m) == 0
        for: 0m
        labels:
          level: warning
          monitor: tendermint_consensus_validator_last_signed_height
        annotations:
          description: "The fx chain node did not participate in the block signing for 2 minutes"

      - alert: The fx chain node missed blocks
        expr: tendermint_consensus_validator_missed_blocks - (tendermint_consensus_validator_missed_blocks offset 2m) >= 3
        for: 5m
        labels:
          level: warning
          monitor: tendermint_consensus_validator_missed_blocks
        annotations:
          description: "The number of blocks not signed by the verifier exceeds the threshold of 100, current: {{$value}}"

      - alert: The fx chain node missing validators
        expr: tendermint_consensus_missing_validators > 10
        for: 1m
        labels:
          level: warning
          monitor: tendermint_consensus_missing_validators
        annotations:
          description: "The fx chain node missing validators number exceeds the threshold 10, current: {{$value}}"

      - alert: The fx chain node byzantine validators
        expr: tendermint_consensus_byzantine_validators > 0
        for: 1m
        labels:
          level: warning
          monitor: tendermint_consensus_byzantine_validators
        annotations:
          description: "The fx chain node byzantine validators number exceeds the threshold 0, current: {{$value}}"

      - alert: The fx chain node block interval seconds
        expr: tendermint_consensus_block_interval_seconds_sum / tendermint_consensus_block_interval_seconds_count > 7
        for: 1m
        labels:
          level: warning
          monitor: tendermint_consensus_block_interval_seconds_(sum/count)
        annotations:
          description: "The fx chain node block interval seconds, current: {{$value}}s"

      - alert: The fx chain node consensus rounds
        expr: tendermint_consensus_rounds > 0
        for: 1m
        labels:
          level: warning
          monitor: tendermint_consensus_rounds
        annotations:
          description: "The fx chain node number of rounds > 0, current: {{$value}}s"

      - alert: The fx chain number of transactions
        expr: tendermint_consensus_num_txs > 100
        for: 1m
        labels:
          level: warning
          monitor: tendermint_consensus_num_txs
        annotations:
          description: "The fx chain number of transactions > 100, current: {{$value}}"

      - alert: The fx chain node mempool number of uncommitted transactions
        expr: tendermint_mempool_size > 100
        for: 1m
        labels:
          level: warning
          monitor: tendermint_mempool_size
        annotations:
          description: "The fx chain node number of uncommitted transactions > 100, current: {{$value}}"

      - alert: The fx chain mempool failed txs number
        expr: tendermint_mempool_failed_txs - (tendermint_mempool_failed_txs offset 1m) > 10
        for: 1m
        labels:
          level: warning
          monitor: tendermint_mempool_failed_txs
        annotations:
          description: "The fx chain failed transactions number in the memory pool has increased by more than 10 in 1 minute, current: {{$value}}"

      - alert: The fx chain node synchronization status
        expr: tendermint_consensus_fast_syncing - (tendermint_consensus_fast_syncing offset 5m) != 0
        for: 3m
        labels:
          level: warning
          monitor: tendermint_consensus_fast_syncing
        annotations:
          description: "The node synchronization status has changed, please check"

      - alert: The fx chain node p2p peers
        expr: tendermint_p2p_peers < 5
        for: 1m
        labels:
          level: warning
          monitor: tendermint_p2p_peers
        annotations:
          description: "The fx chain node p2p peers is lower than 5, current: {{$value}}"
