name: Makefile CI

on:
  push:
    branches: [ testnet/v2.0.x ]
  pull_request:
    branches: [ testnet/v2.0.x ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Go environment
      uses: actions/setup-go@v2.1.4
      with:
        go-version: '^1.18'
    
    - name: Run go mod
      run: make go.sum

    - name: Install golangci-lint
      run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.46.2

    - name: Run make
      run: make
